<?php

namespace Database\Seeders;

use App\Models\District;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class DistrictSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $districts = [
            [
                "division_id" => "3",
                "en_name" => "Dhaka",
                "bn_name" => "ঢাকা",
                "slug" => "dhaka",
                "lat" => "23.7115253",
                "long" => "90.4111451",
            ],
            [
                "division_id" => "3",
                "en_name" => "Faridpur",
                "bn_name" => "ফরিদপুর",
                "slug" => "faridpur",
                "lat" => "23.6070822",
                "long" => "89.8429406",
            ],
            [
                "division_id" => "3",
                "en_name" => "Gazipur",
                "bn_name" => "গাজীপুর",
                "slug" => "gazipur",
                "lat" => "24.0022858",
                "long" => "90.4264283",
            ],
            [
                "division_id" => "3",
                "en_name" => "Gopalganj",
                "bn_name" => "গোপালগঞ্জ",
                "slug" => "gopalganj",
                "lat" => "23.0050857",
                "long" => "89.8266059",
            ],
            [
                "division_id" => "8",
                "en_name" => "Jamalpur",
                "bn_name" => "জামালপুর",
                "slug" => "jamalpur",
                "lat" => "24.937533",
                "long" => "89.937775",
            ],
            [
                "division_id" => "3",
                "en_name" => "Kishoreganj",
                "bn_name" => "কিশোরগঞ্জ",
                "slug" => "kishoreganj",
                "lat" => "24.444937",
                "long" => "90.776575",
            ],
            [
                "division_id" => "3",
                "en_name" => "Madaripur",
                "bn_name" => "মাদারীপুর",
                "slug" => "madaripur",
                "lat" => "23.164102",
                "long" => "90.1896805",
            ],
            [
                "division_id" => "3",
                "en_name" => "Manikganj",
                "bn_name" => "মানিকগঞ্জ",
                "slug" => "manikganj",
                "lat" => "23.8644",
                "long" => "90.0047",
            ],
            [
                "division_id" => "3",
                "en_name" => "Munshiganj",
                "bn_name" => "মুন্সিগঞ্জ",
                "slug" => "munshiganj",
                "lat" => "23.5422",
                "long" => "90.5305",
            ],
            [
                "division_id" => "8",
                "en_name" => "Mymensingh",
                "bn_name" => "ময়মনসিংহ",
                "slug" => "mymensingh",
                "lat" => "24.7471",
                "long" => "90.4203",
            ],
            [
                "division_id" => "3",
                "en_name" => "Narayanganj",
                "bn_name" => "নারায়াণগঞ্জ",
                "slug" => "narayanganj",
                "lat" => "23.63366",
                "long" => "90.496482",
            ],
            [
                "division_id" => "3",
                "en_name" => "Narsingdi",
                "bn_name" => "নরসিংদী",
                "slug" => "narsingdi",
                "lat" => "23.932233",
                "long" => "90.71541",
            ],
            [
                "division_id" => "8",
                "en_name" => "Netrokona",
                "bn_name" => "নেত্রকোণা",
                "slug" => "netrokona",
                "lat" => "24.870955",
                "long" => "90.727887",
            ],
            [
                "division_id" => "3",
                "en_name" => "Rajbari",
                "bn_name" => "রাজবাড়ি",
                "slug" => "rajbari",
                "lat" => "23.7574305",
                "long" => "89.6444665",
            ],
            [
                "division_id" => "3",
                "en_name" => "Shariatpur",
                "bn_name" => "শরীয়তপুর",
                "slug" => "shariatpur",
                "lat" => "23.2423",
                "long" => "90.4348",
            ],
            [
                "division_id" => "8",
                "en_name" => "Sherpur",
                "bn_name" => "শেরপুর",
                "slug" => "sherpur",
                "lat" => "25.0204933",
                "long" => "90.0152966",
            ],
            [
                "division_id" => "3",
                "en_name" => "Tangail",
                "bn_name" => "টাঙ্গাইল",
                "slug" => "tangail",
                "lat" => "24.2513",
                "long" => "89.9167",
            ],
            [
                "division_id" => "5",
                "en_name" => "Bogura",
                "bn_name" => "বগুড়া",
                "slug" => "bogura",
                "lat" => "24.8465228",
                "long" => "89.377755",
            ],
            [
                "division_id" => "5",
                "en_name" => "Joypurhat",
                "bn_name" => "জয়পুরহাট",
                "slug" => "joypurhat",
                "lat" => "25.0968",
                "long" => "89.0227",
            ],
            [
                "division_id" => "5",
                "en_name" => "Naogaon",
                "bn_name" => "নওগাঁ",
                "slug" => "naogaon",
                "lat" => "24.7936",
                "long" => "88.9318",
            ],
            [
                "division_id" => "5",
                "en_name" => "Natore",
                "bn_name" => "নাটোর",
                "slug" => "natore",
                "lat" => "24.420556",
                "long" => "89.000282",
            ],
            [
                "division_id" => "5",
                "en_name" => "Nawabganj",
                "bn_name" => "নবাবগঞ্জ",
                "slug" => "nawabganj",
                "lat" => "24.5965034",
                "long" => "88.2775122",
            ],
            [
                "division_id" => "5",
                "en_name" => "Pabna",
                "bn_name" => "পাবনা",
                "slug" => "pabna",
                "lat" => "23.998524",
                "long" => "89.233645",
            ],
            [
                "division_id" => "5",
                "en_name" => "Rajshahi",
                "bn_name" => "রাজশাহী",
                "slug" => "rajshahi",
                "lat" => "24.3745",
                "long" => "88.6042",
            ],
            [
                "division_id" => "5",
                "en_name" => "Sirajgonj",
                "bn_name" => "সিরাজগঞ্জ",
                "slug" => "sirajgonj",
                "lat" => "24.4533978",
                "long" => "89.7006815",
            ],
            [
                "division_id" => "6",
                "en_name" => "Dinajpur",
                "bn_name" => "দিনাজপুর",
                "slug" => "dinajpur",
                "lat" => "25.6217061",
                "long" => "88.6354504",
            ],
            [
                "division_id" => "6",
                "en_name" => "Gaibandha",
                "bn_name" => "গাইবান্ধা",
                "slug" => "gaibandha",
                "lat" => "25.328751",
                "long" => "89.528088",
            ],
            [
                "division_id" => "6",
                "en_name" => "Kurigram",
                "bn_name" => "কুড়িগ্রাম",
                "slug" => "kurigram",
                "lat" => "25.805445",
                "long" => "89.636174",
            ],
            [
                "division_id" => "6",
                "en_name" => "Lalmonirhat",
                "bn_name" => "লালমনিরহাট",
                "slug" => "lalmonirhat",
                "lat" => "25.9923",
                "long" => "89.2847",
            ],
            [
                "division_id" => "6",
                "en_name" => "Nilphamari",
                "bn_name" => "নীলফামারী",
                "slug" => "nilphamari",
                "lat" => "25.931794",
                "long" => "88.856006",
            ],
            [
                "division_id" => "6",
                "en_name" => "Panchagarh",
                "bn_name" => "পঞ্চগড়",
                "slug" => "panchagarh",
                "lat" => "26.3411",
                "long" => "88.5541606",
            ],
            [
                "division_id" => "6",
                "en_name" => "Rangpur",
                "bn_name" => "রংপুর",
                "slug" => "rangpur",
                "lat" => "25.7558096",
                "long" => "89.244462",
            ],
            [
                "division_id" => "6",
                "en_name" => "Thakurgaon",
                "bn_name" => "ঠাকুরগাঁও",
                "slug" => "thakurgaon",
                "lat" => "26.0336945",
                "long" => "88.4616834",
            ],
            [
                "division_id" => "1",
                "en_name" => "Barguna",
                "bn_name" => "বরগুনা",
                "slug" => "barguna",
                "lat" => "22.0953",
                "long" => "90.1121",
            ],
            [
                "division_id" => "1",
                "en_name" => "Barishal",
                "bn_name" => "বরিশাল",
                "slug" => "barishal",
                "lat" => "22.7010",
                "long" => "90.3535",
            ],
            [
                "division_id" => "1",
                "en_name" => "Bhola",
                "bn_name" => "ভোলা",
                "slug" => "bhola",
                "lat" => "22.685923",
                "long" => "90.648179",
            ],
            [
                "division_id" => "1",
                "en_name" => "Jhalokati",
                "bn_name" => "ঝালকাঠি",
                "slug" => "jhalokati",
                "lat" => "22.6406",
                "long" => "90.1987",
            ],
            [
                "division_id" => "1",
                "en_name" => "Patuakhali",
                "bn_name" => "পটুয়াখালী",
                "slug" => "patuakhali",
                "lat" => "22.3596316",
                "long" => "90.3298712",
            ],
            [
                "division_id" => "1",
                "en_name" => "Pirojpur",
                "bn_name" => "পিরোজপুর",
                "slug" => "pirojpur",
                "lat" => "22.5841",
                "long" => "89.9720",
            ],
            [
                "division_id" => "2",
                "en_name" => "Bandarban",
                "bn_name" => "বান্দরবান",
                "slug" => "bandarban",
                "lat" => "22.1953275",
                "long" => "92.2183773",
            ],
            [
                "division_id" => "2",
                "en_name" => "Brahmanbaria",
                "bn_name" => "ব্রাহ্মণবাড়িয়া",
                "slug" => "brahmanbaria",
                "lat" => "23.9570904",
                "long" => "91.1119286",
            ],
            [
                "division_id" => "2",
                "en_name" => "Chandpur",
                "bn_name" => "চাঁদপুর",
                "slug" => "chandpur",
                "lat" => "23.2332585",
                "long" => "90.6712912",
            ],
            [
                "division_id" => "2",
                "en_name" => "Chattogram",
                "bn_name" => "চট্টগ্রাম",
                "slug" => "chattogram",
                "lat" => "22.335109",
                "long" => "91.834073",
            ],
            [
                "division_id" => "2",
                "en_name" => "Cumilla",
                "bn_name" => "কুমিল্লা",
                "slug" => "cumilla",
                "lat" => "23.4682747",
                "long" => "91.1788135",
            ],
            [
                "division_id" => "2",
                "en_name" => "Cox\'s Bazar",
                "bn_name" => "কক্স বাজার",
                "slug" => "coxs-bazar",
                "lat" => "21.4272",
                "long" => "92.0058",
            ],
            [
                "division_id" => "2",
                "en_name" => "Feni",
                "bn_name" => "ফেনী",
                "slug" => "feni",
                "lat" => "23.0159",
                "long" => "91.3976",
            ],
            [
                "division_id" => "2",
                "en_name" => "Khagrachari",
                "bn_name" => "খাগড়াছড়ি",
                "slug" => "khagrachari",
                "lat" => "23.119285",
                "long" => "91.984663",
            ],
            [
                "division_id" => "2",
                "en_name" => "Lakshmipur",
                "bn_name" => "লক্ষ্মীপুর",
                "slug" => "lakshmipur",
                "lat" => "22.942477",
                "long" => "90.841184",
            ],
            [
                "division_id" => "2",
                "en_name" => "Noakhali",
                "bn_name" => "নোয়াখালী",
                "slug" => "noakhali",
                "lat" => "22.869563",
                "long" => "91.099398",
            ],
            [
                "division_id" => "2",
                "en_name" => "Rangamati",
                "bn_name" => "রাঙ্গামাটি",
                "slug" => "rangamati",
                "lat" => "22.7324",
                "long" => "92.2985",
            ],
            [
                "division_id" => "7",
                "en_name" => "Habiganj",
                "bn_name" => "হবিগঞ্জ",
                "slug" => "habiganj",
                "lat" => "24.374945",
                "long" => "91.41553",
            ],
            [
                "division_id" => "7",
                "en_name" => "Maulvibazar",
                "bn_name" => "মৌলভীবাজার",
                "slug" => "maulvibazar",
                "lat" => "24.482934",
                "long" => "91.777417",
            ],
            [
                "division_id" => "7",
                "en_name" => "Sunamganj",
                "bn_name" => "সুনামগঞ্জ",
                "slug" => "sunamganj",
                "lat" => "25.0658042",
                "long" => "91.3950115",
            ],
            [
                "division_id" => "7",
                "en_name" => "Sylhet",
                "bn_name" => "সিলেট",
                "slug" => "sylhet",
                "lat" => "24.8897956",
                "long" => "91.8697894",
            ],
            [
                "division_id" => "4",
                "en_name" => "Bagerhat",
                "bn_name" => "বাগেরহাট",
                "slug" => "bagerhat",
                "lat" => "22.651568",
                "long" => "89.785938",
            ],
            [
                "division_id" => "4",
                "en_name" => "Chuadanga",
                "bn_name" => "চুয়াডাঙ্গা",
                "slug" => "chuadanga",
                "lat" => "23.6401961",
                "long" => "88.841841",
            ],
            [
                "division_id" => "4",
                "en_name" => "Jashore",
                "bn_name" => "যশোর",
                "slug" => "jashore",
                "lat" => "23.16643",
                "long" => "89.2081126",
            ],
            [
                "division_id" => "4",
                "en_name" => "Jhenaidah",
                "bn_name" => "ঝিনাইদহ",
                "slug" => "jhenaidah",
                "lat" => "23.5448176",
                "long" => "89.1539213",
            ],
            [
                "division_id" => "4",
                "en_name" => "Khulna",
                "bn_name" => "খুলনা",
                "slug" => "khulna",
                "lat" => "22.815774",
                "long" => "89.568679",
            ],
            [
                "division_id" => "4",
                "en_name" => "Kushtia",
                "bn_name" => "কুষ্টিয়া",
                "slug" => "kushtia",
                "lat" => "23.901258",
                "long" => "89.120482",
            ],
            [
                "division_id" => "4",
                "en_name" => "Magura",
                "bn_name" => "মাগুরা",
                "slug" => "magura",
                "lat" => "23.487337",
                "long" => "89.419956",
            ],
            [
                "division_id" => "4",
                "en_name" => "Meherpur",
                "bn_name" => "মেহেরপুর",
                "slug" => "meherpur",
                "lat" => "23.762213",
                "long" => "88.631821",
            ],
            [
                "division_id" => "4",
                "en_name" => "Narail",
                "bn_name" => "নড়াইল",
                "slug" => "narail",
                "lat" => "23.172534",
                "long" => "89.512672",
            ],
            [
                "division_id" => "4",
                "en_name" => "Satkhira",
                "bn_name" => "সাতক্ষীরা",
                "slug" => "satkhira",
                "lat" => "22.7185",
                "long" => "89.0705",
            ],
        ];

        foreach ($districts as $districtData) {
            District::create($districtData);
        }
    }
}
